namespace Sqlbi.Bravo.Infrastructure;

/// <summary>
/// Provides application version information generated by Nerdbank.GitVersioning from <c>version.json</c>.
/// </summary>
internal static class AppVersion
{
    /// <summary>
    /// Four-part file version in the form <c>Major.Minor.Patch.Height</c>, where <c>Height</c>
    /// distinguishes builds of the same version.
    /// </summary>
    public static string FileVersion { get; } = ThisAssembly.AssemblyFileVersion;

    /// <summary>
    /// Semantic version of the application, including the prerelease label when present and
    /// excluding build metadata, for example <c>1.1.0-beta.1</c> or <c>1.1.0</c>.
    /// Internal builds include the Git commit identifier, for example
    /// <c>1.1.0-beta.1.g1c52e441d1</c>, or <c>1.1.0-g1c52e441d1</c> without a prerelease label.
    /// </summary>
    public static string SemanticVersion { get; } = ThisAssembly.NuGetPackageVersion;

    /// <summary>
    /// Informational version of the application, including the file version, prerelease label
    /// when present, and Git commit identifier, for example <c>1.1.0.14-beta.1+1c52e441d1</c>.
    /// </summary>
    public static string InformationalVersion { get; } = ThisAssembly.AssemblyInformationalVersion;
}
