parameters:
- name: verbosity
  displayName: Verbosity
  type: string
  default: normal
  values:
  - minimal
  - normal
  - detailed
  - diagnostic

trigger: none

strategy:
  matrix:
    bravo-x64:
      arch: 'x64'
      selfcontained: 'true'
      publishmode: 'SELFCONTAINED'
      artifactSuffix: 'x64'
    bravo-x64-frameworkdependent:
      arch: 'x64'
      selfcontained: 'false'
      publishmode: 'FRAMEWORKDEPENDENT'
      artifactSuffix: 'x64-frameworkdependent'

pool:
  vmImage: 'windows-latest'

variables:
  csproj: 'src/Bravo.csproj'
  configuration: 'Release'
  installerSourcesDirectory: '$(Build.SourcesDirectory)\installer\wix\src\Bravo'

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: false
  clean: true
  
- script: nbgv cloud --all-vars
  displayName: nbgv setup
  workingDirectory: '$(Build.SourcesDirectory)'

- bash: |
    artifact="Bravo.$(NBGV_SimpleVersion).$(artifactSuffix)"
    echo "##vso[task.setvariable variable=artifact]$artifact"
    echo "Artifact name: $artifact"
    echo "=== ENVIRONMENT VARIABLES ==="
    printenv
  displayName: 'Compute variables'

- script: dotnet --info
  displayName: dotnet info
- script: dotnet restore "$(csproj)" --runtime "win-$(arch)" --verbosity "${{ parameters.verbosity }}"
  displayName: dotnet restore
- script: dotnet publish "$(csproj)" --configuration "$(configuration)" --no-restore --runtime "win-$(arch)" --self-contained "$(selfcontained)" --output "$(Build.BinariesDirectory)" --verbosity "${{ parameters.verbosity }}" /p:ContinuousIntegrationBuild="true" /p:AdditionalConstants="$(publishmode)"
  displayName: dotnet publish
- script: dotnet tool install --global AzureSignTool
  displayName: dotnet install AzureSignTool
- task: CmdLine@2
  displayName: 'Code signing EXE'
  inputs:
    script: 'AzureSignTool sign -kvu "$(SigningVaultURL)" -kvt "$(SigningTenantId)" -kvi "$(SigningClientId)" -kvs "$(SigningClientSecret)" -kvc "$(SigningCertName)" -tr http://timestamp.digicert.com -v "$(Build.BinariesDirectory)\Bravo.exe"'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'WiX harvest components'
  inputs:
    script: '"%WIX%bin\heat.exe" dir "$(Build.BinariesDirectory)" -gg -scom -srd -sreg -sfrag -template fragment -cg ComponentsAutogenerated -dr INSTALLFOLDER -var var.PublishFolder -t Bravo.xslt -out Components.wxs'
    workingDirectory: '$(installerSourcesDirectory)'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'WiX compile components'
  inputs:
    script: '"%WIX%bin\candle.exe" Components.wxs -dPublishFolder="$(Build.BinariesDirectory)" -arch "$(arch)"'
    workingDirectory: '$(installerSourcesDirectory)'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'WiX compile app'
  inputs:
    script: '"%WIX%bin\candle.exe" Bravo.wxs -dPublishFolder="$(Build.BinariesDirectory)" -dVersion="$(NBGV_AssemblyFileVersion)" -arch "$(arch)"'
    workingDirectory: '$(installerSourcesDirectory)'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'WiX compile app (perUser)'
  inputs:
    script: '"%WIX%bin\candle.exe" Bravo-perUser.wxs -dPublishFolder="$(Build.BinariesDirectory)" -dVersion="$(NBGV_AssemblyFileVersion)" -arch "$(arch)"'
    workingDirectory: '$(installerSourcesDirectory)'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'WiX linker MSI'
  inputs:
    # -sice:ICE03 is used to ignore -> warning LGHT1076 : ICE03: String overflow (greater than length permitted in column). These warnings are expected and can be safely ignored
    # -sice:ICE60 is used to ignore -> warning LGHT1076 : ICE60: The file filE8E88FBC49DC5621FF3FC1B65ADCCB39 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
    # -sice:ICE61 is used to ignore -> warning LGHT1076 : ICE61: This product should remove only older versions of itself. The Maximum version is not less than the current product.
    # -sice:ICE80 is used to ignore -> error   LGHT0204 : ICE80: This 64BitComponent pbitool.json uses 32BitDirectory POWERBIEXTERNALTOOLSFOLDER
    script: '"%WIX%bin\light.exe" Bravo.wixobj Components.wixobj -ext WixUIExtension.dll -ext WixUtilExtension.dll -dPublishFolder="$(Build.BinariesDirectory)" -cultures:en-us -loc Bravo-en-us.wxl -out "$(Build.ArtifactStagingDirectory)\$(artifact).msi" -spdb -sice:ICE03 -sice:ICE60 -sice:ICE61 -sice:ICE80'
    workingDirectory: '$(installerSourcesDirectory)'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'WiX linker MSI (perUser)'
  inputs:
    # -sice:ICE57 is used to ignore -> error   LGHT0204 : ICE57: Component 'app.exe' has both per-user and per-machine data with a per-machine KeyPath.
    # -sice:ICE60 is used to ignore -> warning LGHT1076 : ICE60: The file filE8E88FBC49DC5621FF3FC1B65ADCCB39 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
    # -sice:ICE61 is used to ignore -> warning LGHT1076 : ICE61: This product should remove only older versions of itself. The Maximum version is not less than the current product.
    # -sice:ICE80 is used to ignore -> error   LGHT0204 : ICE80: This 64BitComponent [...] uses 32BitDirectory [...]
    script: '"%WIX%bin\light.exe" Bravo-perUser.wixobj Components.wixobj -ext WixUIExtension.dll -ext WixUtilExtension.dll -dPublishFolder="$(Build.BinariesDirectory)" -cultures:en-us -loc Bravo-en-us.wxl -out "$(Build.ArtifactStagingDirectory)\$(artifact)-userinstaller.msi" -spdb -sice:ICE57 -sice:ICE60 -sice:ICE61 -sice:ICE80'
    workingDirectory: '$(installerSourcesDirectory)'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'Code signing MSI'
  inputs:
    script: 'AzureSignTool sign -kvu "$(SigningVaultURL)" -kvt "$(SigningTenantId)" -kvi "$(SigningClientId)" -kvs "$(SigningClientSecret)" -kvc "$(SigningCertName)" -tr http://timestamp.digicert.com -v "$(Build.ArtifactStagingDirectory)\$(artifact).msi"'
    failOnStderr: true
- task: CmdLine@2
  displayName: 'Code signing MSI (perUser)'
  inputs:
    script: 'AzureSignTool sign -kvu "$(SigningVaultURL)" -kvt "$(SigningTenantId)" -kvi "$(SigningClientId)" -kvs "$(SigningClientSecret)" -kvc "$(SigningCertName)" -tr http://timestamp.digicert.com -v "$(Build.ArtifactStagingDirectory)\$(artifact)-userinstaller.msi"'
    failOnStderr: true
- task: ArchiveFiles@2
  displayName: 'Portable ZIP archive'
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifact)-portable.zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts to DevOps Pipeline'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'