@ECHO OFF
SETLOCAL

REM Enable windows installer logging
REM    msiexec /i "C:\temp\installer.msi" /L*V "C:\temp\file.log"

SET arch=x64
SET configuration=Release
SET verbosity=Minimal & :: Minimal,Normal,Diagnostic,Detailed
SET wixheat="%~dp0installer\wix\bin\heat.exe"
SET wixlight="%~dp0installer\wix\bin\light.exe"
SET wixcandle="%~dp0installer\wix\bin\candle.exe"
SET msbuild="%WINDIR%\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe"

REM ***
REM *** BRAVO BUILD
REM ***
ECHO *** BRAVO BUILD ***
SET runtime=win-%arch%
SET framework=net5-windows10.0.17763.0
SET publishfolder=%~dp0src\bin\%configuration%\%framework%\%runtime%\publish
CD /d "%~dp0src"
IF EXIST %publishfolder% RMDIR /s /q %publishfolder%
dotnet publish Bravo.csproj --configuration %configuration% --runtime %runtime% --output %publishfolder% --self-contained true --verbosity %verbosity% --force --nologo || GOTO :error

REM ***
REM *** BRAVO INSTALLER
REM ***
ECHO *** BRAVO INSTALLER ***
CD /d "%~dp0installer\wix\src\Bravo"
IF EXIST *.msi    DEL *.msi
IF EXIST *.wixobj DEL *.wixobj
IF EXIST *.wixpdb DEL *.wixpdb
"%wixheat%" dir "%publishfolder%" -gg -scom -srd -sreg -sfrag -templatefragment -cg ComponentsAutogenerated -dr INSTALLFOLDER -var var.PublishFolder -t Bravo.xslt -out Components.wxs -nologo || GOTO :error
"%wixcandle%" Components.wxs -dPublishFolder="%publishfolder%" -arch "%arch%" -nologo || GOTO :error
"%wixcandle%" Bravo.wxs -arch "%arch%" -dPublishFolder="%publishfolder%" -nologo || GOTO :error
REM light -sice:ICE60 is used to ignore -> warning LGHT1076 : ICE60: The file filE8E88FBC49DC5621FF3FC1B65ADCCB39 is not a Font, and its version is not a companion file reference. It should have a language specified in the Language column.
REM light -sice:ICE61 is used to ignore -> warning LGHT1076 : ICE61: This product should remove only older versions of itself. The Maximum version is not less than the current product.
REM light -sice:ICE80 is used to ignore -> error LGHT0204 : ICE80: This 64BitComponent pbitool.json uses 32BitDirectory POWERBIEXTERNALTOOLSFOLDER
"%wixlight%" Bravo.wixobj Components.wixobj -ext WixUIExtension.dll -ext WixUtilExtension.dll -cultures:en-us -loc Bravo-en-us.wxl -out "Bravo-%arch%-en-us.msi" -sice:ICE60 -sice:ICE61 -sice:ICE80 -nologo || GOTO :error

REM ***
REM *** STORELAUNCHER BUILD
REM ***
ECHO *** STORELAUNCHER BUILD ***
SET publishfolder=%~dp0installer\msix\Bravo.Installer.Msix.StoreLauncher\bin\%configuration%
CD /d "%~dp0installer\msix\Bravo.Installer.Msix.StoreLauncher"
"%msbuild%" /target:Clean;Rebuild /property:Configuration=%configuration% /verbosity:%verbosity% /toolsversion:4.0 /nologo Bravo.Installer.Msix.StoreLauncher.csproj || GOTO :error

REM ***
REM *** STORELAUNCHER INSTALLER
REM ***
ECHO *** STORELAUNCHER INSTALLER ***
CD /d "%~dp0installer\wix\src\BravoStoreLauncher"
IF EXIST *.msi    DEL *.msi
IF EXIST *.wixobj DEL *.wixobj
IF EXIST *.wixpdb DEL *.wixpdb
"%wixcandle%" BravoStoreLauncher.wxs -arch "%arch%" -dPublishFolder="%publishfolder%" -nologo || GOTO :error
REM light -sice:ICE61 is used to ignore -> warning LGHT1076 : ICE61: This product should remove only older versions of itself. The Maximum version is not less than the current product.
REM light -sice:ICE80 is used to ignore -> error LGHT0204 : ICE80: This 64BitComponent pbitool.json uses 32BitDirectory POWERBIEXTERNALTOOLSFOLDER
"%wixlight%" BravoStoreLauncher.wixobj -ext WixUIExtension.dll -cultures:en-us -loc BravoStoreLauncher-en-us.wxl -out "BravoStoreLauncher-%arch%-en-us.msi" -sice:ICE61 -sice:ICE80 -nologo || GOTO :error

REM ***
REM *** EXIT
REM ***
ECHO *** COMPLETED ***
GOTO :EOF
:error
ECHO !!! ERROR !!!
EXIT /b %ERRORLEVEL%
