@ECHO OFF
SETLOCAL

SET arch=x64
SET runtime=win-%arch%
SET framework=net5-windows10.0.17763.0
SET configuration=Release
SET verbosity=Minimal
SET publishfolder=%~dp0src\bin\%configuration%\%framework%\%runtime%\publish

CD /d "%~dp0"
IF EXIST %publishfolder% RMDIR /s /q %publishfolder%
dotnet publish .\src\Bravo.csproj --configuration %configuration% --runtime %runtime% --output %publishfolder% --self-contained true --verbosity %verbosity% --force --nologo

REM Enable windows installer logging
REM    msiexec /i "C:\temp\installer.msi" /L*V "C:\temp\file.log"

CD /d "%~dp0installer\wix"
IF EXIST *.msi    DEL *.msi
IF EXIST *.wixobj DEL *.wixobj
IF EXIST *.wixpdb DEL *.wixpdb
.\bin\heat.exe dir "%publishfolder%" -gg -scom -srd -sreg -sfrag -templatefragment -cg ComponentsAutogenerated -dr INSTALLFOLDER -var var.PublishFolder -t Bravo.xslt -out Components.wxs -nologo
.\bin\candle.exe Components.wxs -dPublishFolder="%publishfolder%" -arch "%arch%" -nologo
.\bin\candle.exe Bravo.wxs -arch "%arch%" -dPublishFolder="%publishfolder%" -nologo
.\bin\light.exe Bravo.wixobj Components.wixobj -ext WixUIExtension.dll -ext WixUtilExtension.dll -cultures:en-us -loc Bravo_en-us.wxl -out "Bravo-%arch%-en-us.msi" -sice:ICE61 -sice:ICE80 -nologo

EXIT /b %ERRORLEVEL%
