/*!
 * Bravo for Power BI
 * Copyright (c) SQLBI corp. - All rights reserved.
 * https://www.sqlbi.com
*/
export declare const strings: {
    appUrl: string;
    appGithubUrl: string;
    daxFormatterUrl: string;
    appName: string;
    menuCtrlTitle: string;
    addCtrlTitle: string;
    daxFormatterName: string;
    daxFormatterTitle: string;
    analyzeModelName: string;
    manageDatesName: string;
    manageDatesTitle: string;
    exportDataName: string;
    exportDataTitle: string;
    bestPracticesName: string;
    bestPracticesTitle: string;
    settingsCtrlTitle: string;
    helpCtrlTitle: string;
    themeCtrlTitle: string;
    filterUnrefCtrlTitle: string;
    groupByTableCtrlTitle: string;
    expandAllCtrlTitle: string;
    collapseAllCtrlTitle: string;
    saveVpaxCtrlTile: string;
    refreshCtrlTitle: string;
    defaultTabName: string;
    welcomeTitle: string;
    welcomeText: string;
    welcomeHelpTitle: string;
    welcomeHelpText: string;
    helpConnectVideo: string;
    openSourcePayoff: string;
    quickActionAttachPBITitle: string;
    quickActionConnectPBITitle: string;
    quickActionOpenVPXTitle: string;
    connectDialogTitle: string;
    connectDialogAttachPBILabel: string;
    connectDialogConnectPBILabel: string;
    connectDialogOpenVPXLabel: string;
    connectDragFile: string;
    connectBrowse: string;
    connectNoReports: string;
    dialogOK: string;
    dialogCancel: string;
    dialogOpen: string;
    confirmTabCloseMessage: string;
    analyzeModelSummary: (size: number | string, columnsCount: number | string, unreferecedCount: number | string) => string;
    analyzeModelTableColColumn: string;
    analyzeModelTableColTable: string;
    analyzeModelTableColEntity: string;
    analyzeModelTableColSize: string;
    analyzeModelTableColWeight: string;
    analyzeModelTableColCardinality: string;
    analyzeModelTableColCardinalityTooltip: string;
    analyzeModelTableColRows: string;
    otherColumnsRowName: string;
    aggregatedTableName: string;
    columnWarningExplanation: string;
    columnWarningTooltip: string;
    daxFormatterSummary: (count: number) => string;
    daxFormatterTableColMeasure: string;
    daxFormatterTableColTable: string;
    daxFormatterTableSelected: (count: number) => string;
    daxFormatterOriginalCode: string;
    daxFormatterFormattedCode: string;
    daxFormatterFormat: string;
    daxFormatterAgreement: string;
    daxFormatterPreviewDesc: string;
    daxFormatterPreviewAllOption: string;
    daxFormatterPreviewButton: string;
    dataUsageLink: string;
    dataUsageTitle: string;
    dataUsageMessage: string;
    signIn: string;
    searchPlaceholder: string;
    searchColumnPlaceholder: string;
    previewPlaceholder: string;
    errorTitle: string;
    errorGeneric: string;
    errorUnspecified: string;
    errorNotConnected: string;
    errorDatasetListing: string;
};
