name: 🐛 Bug Report
labels: ["bug", "untriaged"]
description: Let us know if something is expected to work, but doesn't.
body:
  - type: markdown
    attributes:
      value: |
        Before opening a bug report please search for the behaviour in the existing issues.
        
        ---
  - type: textarea
    id: describe-problem
    attributes:
      label: Describe the problem
      description:
        Describe the issue you are experiencing with Bravo for Power BI. 
        Provide a clear and concise description of what you were trying to do and what happened, along with any error messages you encountered.
    validations:
      required: true
  - type: input
    id: application-version
    attributes:
      label: Bravo version
      description:
        Go to the settings panel and select `Options` > `About` menu item to see the Bravo for Power BI version.
    validations:
      required: true
  - type: dropdown
    id: tabular-model
    attributes:
      label: Tabular model
      description: Select the tabular model you are using
      options:
        - Power BI Desktop, import mode
        - Power BI Dataset
    validations:
      required: true
  - type: input
    id: powerbi
    attributes:
      label: Power BI
      description:
        Enter the specific Power BI engine and version used (e.g. `Power BI Desktop version March 2022`, `Azure Analysis Services`, `SSAS 2019`)
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the behavior
      description: Provide steps to reproduce the problem you are experiencing.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description:
        Add any other context about the problem you are experiencing here.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain your problem, if applicable.
  - type: textarea
    id: logs
    attributes:
      label: Anything else ?
      description:
        Links ? References ? Anything that will give us more context about the issue you are encountering.
        You can enter  a message text from the application diagnostic or upload a diagnostic log file, if applicable. 
        To enable the application diagnostic go to the settings panel and select `Options` > `Diagnostics`.
      placeholder:
        You can attach log files by clicking this area to highlight it and then dragging the files in.
